[build]
  publish = "."

[context.beta]
  publish = "."


# beta deploy trigger 2


[context.branch-deploy]
  publish = "."

# force beta branch deploy 1789906161625


[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
